# Generated by Django 4.1 on 2024-02-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='car_id')),
                ('brand', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('color', models.CharField(max_length=20)),
                ('seat', models.PositiveIntegerField()),
                ('vehicle_no', models.CharField(max_length=15)),
                ('transmission', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarFile',
            fields=[
                ('car_file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=5)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'car_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('file_path', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chat_room_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chat_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('id_card', models.CharField(max_length=200, verbose_name='idCard')),
                ('license_card', models.CharField(max_length=200, verbose_name='licenseCard')),
                ('phone_number', models.CharField(max_length=200, verbose_name='phoneNumber')),
                ('status', models.CharField(max_length=200, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('pickup_location', models.CharField(max_length=100)),
                ('return_location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15)),
                ('transport_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('damage_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('transaction_datetime', models.DateTimeField()),
                ('deposit_return_time', models.DateTimeField(blank=True, null=True)),
                ('refund_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='phoneNumber')),
                ('status', models.CharField(blank=True, max_length=15, null=True, verbose_name='status')),
                ('balance', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('approved_datetime', models.DateTimeField(blank=True, null=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'provider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('withdrawal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('withdraw_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'withdrawal',
                'managed': False,
            },
        ),
    ]
